export const PERMISSION_ACTIONS = ['view', 'create', 'edit', 'delete', 'approve'];

export const DEFAULT_ROLES = [
  {
    slug: 'owner_admin',
    name: 'Owner/Admin',
    description: 'Full system access including user and role management',
    isSystem: true,
    allPermissions: true,
  },
  {
    slug: 'manager',
    name: 'Manager',
    description: 'Operational management with limited admin access',
    isSystem: true,
    permissionKeys: [
      'core.dashboard.view',
      'core.company.view', 'core.company.edit',
      'core.users.view', 'core.users.create', 'core.users.edit',
      'core.roles.view',
      'core.audit_log.view',
      'core.approvals.view', 'core.approvals.create', 'core.approvals.edit', 'core.approvals.approve',
      'pos.sales.view', 'pos.sales.create', 'pos.terminal.view', 'sales.orders.view',
      'sales.agents.view', 'sales.agents.create', 'sales.agents.edit',
      'sales.commissions.view', 'sales.commissions.create', 'sales.commissions.edit', 'sales.commissions.approve',
      'sales.commission_payments.view', 'sales.commission_payments.create', 'sales.commission_payments.approve',
      'sales.commission_reports.view',
      'pos.returns.view', 'pos.returns.create',
      'pos.quotations.view', 'pos.quotations.create', 'pos.quotations.edit', 'pos.quotations.approve',
      'purchases.orders.view', 'purchases.orders.create', 'purchases.orders.edit', 'purchases.orders.approve',
      'purchases.bills.view', 'purchases.bills.create',
      'purchases.price_lists.view', 'purchases.price_lists.create',
      'purchases.returns.view', 'purchases.returns.create',
      'purchases.reports.view',
      'products.products.view', 'products.products.create', 'products.products.edit',
      'products.categories.view', 'products.categories.create', 'products.categories.edit',
      'products.brands.view', 'products.brands.create', 'products.brands.edit',
      'products.units.view', 'products.units.create', 'products.units.edit',
      'inventory.stock.view', 'inventory.movements.view', 'inventory.movements.create', 'inventory.movements.approve',
      'inventory.adjustments.view', 'inventory.adjustments.create', 'inventory.adjustments.approve',
      'warehouse.warehouses.view', 'warehouse.locations.view',
      'warehouse.transfers.view', 'warehouse.transfers.create', 'warehouse.transfers.approve',
      'warehouse.stock_counts.view', 'warehouse.occupancy.view',
      'parties.customers.view', 'parties.customers.create', 'parties.customers.edit',
      'parties.suppliers.view', 'parties.suppliers.create', 'parties.suppliers.edit',
      'parties.customer_receipts.view', 'parties.customer_receipts.create', 'parties.customer_receipts.edit', 'parties.customer_receipts.approve',
      'parties.supplier_payments.view', 'parties.supplier_payments.create', 'parties.supplier_payments.edit', 'parties.supplier_payments.approve',
      'crm.contacts.view',
      'finance.ledger.view', 'finance.ledger.create',
      'finance.bank_import.view', 'finance.bank_import.create', 'finance.bank_import.edit', 'finance.bank_import.approve',
      'hr.employees.view', 'hr.attendance.view', 'hr.attendance.create',
      'hr.wages.view', 'hr.wages.create',
      'reports.reports.view',
      // CEO dashboard is NOT granted by default — assign reports.ceo_dashboard.view explicitly
    ],
  },
  {
    slug: 'cashier',
    name: 'Cashier',
    description: 'POS terminal only — no inventory adjustments, CEO dashboard, or administration',
    isSystem: true,
    permissionKeys: [
      'core.dashboard.view',
      'pos.terminal.view', 'pos.sales.view', 'pos.sales.create',
      'pos.returns.view', 'pos.returns.create',
      'pos.quotations.view', 'pos.quotations.create', 'pos.quotations.approve',
      'products.products.view',
      'parties.customers.view', 'parties.customers.create',
    ],
  },
  {
    slug: 'warehouse_manager',
    name: 'Warehouse Manager',
    description: 'Warehouse and inventory management',
    isSystem: true,
    permissionKeys: [
      'core.dashboard.view',
      'products.products.view',
      'inventory.stock.view', 'inventory.movements.view', 'inventory.movements.create', 'inventory.movements.edit', 'inventory.movements.approve',
      'inventory.adjustments.view', 'inventory.adjustments.create', 'inventory.adjustments.approve',
      'warehouse.warehouses.view', 'warehouse.warehouses.edit', 'warehouse.warehouses.create',
      'warehouse.locations.view', 'warehouse.locations.create', 'warehouse.locations.edit',
      'warehouse.transfers.view', 'warehouse.transfers.create', 'warehouse.transfers.edit', 'warehouse.transfers.approve',
      'warehouse.stock_counts.view', 'warehouse.stock_counts.create', 'warehouse.stock_counts.edit', 'warehouse.stock_counts.approve',
      'warehouse.occupancy.view',
      'parties.suppliers.view', 'parties.suppliers.create', 'parties.suppliers.edit',
    ],
  },
  {
    slug: 'warehouse_staff',
    name: 'Warehouse Staff',
    description: 'Warehouse operations without approval rights',
    isSystem: true,
    permissionKeys: [
      'core.dashboard.view',
      'products.products.view',
      'inventory.stock.view', 'inventory.movements.view', 'inventory.movements.create',
      'warehouse.warehouses.view',
      'warehouse.locations.view',
      'warehouse.transfers.view', 'warehouse.transfers.create',
      'warehouse.stock_counts.view', 'warehouse.stock_counts.create',
      'warehouse.occupancy.view',
    ],
  },
  {
    slug: 'sales_staff',
    name: 'Sales Staff',
    description: 'Sales and customer management',
    isSystem: true,
    permissionKeys: [
      'core.dashboard.view',
      'products.products.view',
      'parties.customers.view', 'parties.customers.create', 'parties.customers.edit',
      'parties.customer_receipts.view', 'parties.customer_receipts.create', 'parties.customer_receipts.edit', 'parties.customer_receipts.approve',
      'crm.contacts.view',
      'pos.sales.view', 'pos.terminal.view', 'sales.orders.view', 'pos.sales.create',
      'pos.quotations.view', 'pos.quotations.create', 'pos.quotations.edit', 'pos.quotations.approve',
      'reports.reports.view',
    ],
  },
  {
    slug: 'accountant',
    name: 'Accountant',
    description: 'Financial reporting and audit access',
    isSystem: true,
    permissionKeys: [
      'core.dashboard.view',
      'core.audit_log.view',
      'core.approvals.view', 'core.approvals.approve',
      'reports.reports.view', 'reports.ceo_dashboard.view',
      'finance.ledger.view', 'finance.ledger.create', 'finance.ledger.edit',
      'finance.bank_import.view', 'finance.bank_import.create', 'finance.bank_import.edit', 'finance.bank_import.approve',
      'hr.employees.view', 'hr.attendance.view', 'hr.wages.view', 'hr.wages.create', 'hr.wages.edit',
      'pos.sales.view', 'sales.orders.view',
      'sales.agents.view', 'sales.commissions.view', 'sales.commission_payments.view', 'sales.commission_reports.view',
      'purchases.orders.view', 'purchases.bills.view', 'purchases.reports.view',
      'inventory.movements.view',
      'parties.customers.view', 'parties.suppliers.view', 'crm.contacts.view',
      'parties.customer_receipts.view', 'parties.customer_receipts.create', 'parties.customer_receipts.edit', 'parties.customer_receipts.approve',
      'parties.supplier_payments.view', 'parties.supplier_payments.create', 'parties.supplier_payments.edit', 'parties.supplier_payments.approve',
    ],
  },
  {
    slug: 'viewer',
    name: 'Viewer',
    description: 'Read-only access across modules',
    isSystem: true,
    viewOnly: true,
  },
];

export const MODULE_DEFINITIONS = [
  {
    code: 'core',
    name: 'Core System',
    sortOrder: 1,
    features: [
      { code: 'dashboard', name: 'Dashboard', actions: ['view'] },
      { code: 'company', name: 'Company Setup', actions: ['view', 'create', 'edit'] },
      { code: 'users', name: 'User Management', actions: ['view', 'create', 'edit', 'delete'] },
      { code: 'roles', name: 'Role Management', actions: ['view', 'create', 'edit', 'delete'] },
      { code: 'audit_log', name: 'Audit Log', actions: ['view'] },
      { code: 'approvals', name: 'Approvals', actions: ['view', 'create', 'edit', 'approve'] },
      { code: 'system_settings', name: 'System Settings', actions: ['view', 'edit'] },
      { code: 'document_numbering', name: 'Document Numbering', actions: ['view', 'edit'] },
      { code: 'data_export', name: 'Data Export', actions: ['view', 'create'] },
    ],
  },
  {
    code: 'products',
    name: 'Product Management',
    sortOrder: 2,
    features: [
      { code: 'products', name: 'Products', actions: ['view', 'create', 'edit', 'delete', 'approve'] },
      { code: 'categories', name: 'Categories', actions: ['view', 'create', 'edit', 'delete'] },
      { code: 'brands', name: 'Brands', actions: ['view', 'create', 'edit', 'delete'] },
      { code: 'units', name: 'Units', actions: ['view', 'create', 'edit', 'delete'] },
    ],
  },
  {
    code: 'inventory',
    name: 'Inventory Management',
    sortOrder: 3,
    features: [
      { code: 'stock', name: 'Stock Levels', actions: ['view'] },
      { code: 'movements', name: 'Inventory Movements', actions: ['view', 'create', 'edit', 'delete', 'approve'] },
      { code: 'adjustments', name: 'Stock Adjustments', actions: ['view', 'create', 'edit', 'approve'] },
    ],
  },
  {
    code: 'warehouse',
    name: 'Warehouse Management',
    sortOrder: 4,
    features: [
      { code: 'warehouses', name: 'Warehouses', actions: ['view', 'create', 'edit', 'delete'] },
      { code: 'locations', name: 'Locations', actions: ['view', 'create', 'edit', 'delete'] },
      { code: 'transfers', name: 'Transfers', actions: ['view', 'create', 'edit', 'delete', 'approve'] },
      { code: 'stock_counts', name: 'Stock Counts', actions: ['view', 'create', 'edit', 'approve'] },
      { code: 'occupancy', name: 'Occupancy', actions: ['view'] },
    ],
  },
  {
    code: 'pos',
    name: 'Point of Sale',
    sortOrder: 5,
    features: [
      { code: 'terminal', name: 'POS Terminal', actions: ['view', 'create'] },
      { code: 'sales', name: 'Sales', actions: ['view', 'create', 'edit', 'delete', 'approve'] },
      { code: 'returns', name: 'Returns', actions: ['view', 'create', 'edit', 'approve'] },
      { code: 'quotations', name: 'Quotations', actions: ['view', 'create', 'edit', 'delete', 'approve'] },
      { code: 'pricing', name: 'POS Pricing', actions: ['edit', 'approve'] },
      { code: 'devices', name: 'POS Devices & Sync', actions: ['view', 'create', 'edit', 'delete', 'approve'] },
    ],
  },
  {
    code: 'sales',
    name: 'Sales Management',
    sortOrder: 6,
    features: [
      { code: 'orders', name: 'Sales Orders', actions: ['view', 'create', 'edit', 'delete', 'approve'] },
      { code: 'agents', name: 'Sales Agents', actions: ['view', 'create', 'edit', 'delete'] },
      { code: 'commissions', name: 'Commissions', actions: ['view', 'create', 'edit', 'approve'] },
      { code: 'commission_payments', name: 'Commission Payments', actions: ['view', 'create', 'edit', 'approve', 'delete'] },
      { code: 'commission_reports', name: 'Commission Reports', actions: ['view'] },
    ],
  },
  {
    code: 'purchases',
    name: 'Purchase Management',
    sortOrder: 7,
    features: [
      { code: 'orders', name: 'Purchase Orders', actions: ['view', 'create', 'edit', 'delete', 'approve'] },
      { code: 'bills', name: 'Purchase Bills', actions: ['view', 'create', 'edit', 'delete', 'approve'] },
      { code: 'price_lists', name: 'Supplier Price Lists', actions: ['view', 'create', 'edit'] },
      { code: 'returns', name: 'Purchase Returns', actions: ['view', 'create', 'edit'] },
      { code: 'reports', name: 'Purchase Reports', actions: ['view'] },
    ],
  },
  {
    code: 'crm',
    name: 'CRM',
    sortOrder: 8,
    features: [
      { code: 'contacts', name: 'Contacts', actions: ['view', 'create', 'edit', 'delete'] },
    ],
  },
  {
    code: 'finance',
    name: 'Finance',
    sortOrder: 9,
    features: [
      { code: 'ledger', name: 'Finance', actions: ['view', 'create', 'edit', 'delete', 'approve'] },
      { code: 'bank_import', name: 'Bank Statement Import', actions: ['view', 'create', 'edit', 'approve'] },
    ],
  },
  {
    code: 'hr',
    name: 'HR & Wages',
    sortOrder: 9.5,
    features: [
      { code: 'employees', name: 'Employees', actions: ['view', 'create', 'edit', 'delete'] },
      { code: 'attendance', name: 'Attendance', actions: ['view', 'create', 'edit', 'approve'] },
      { code: 'wages', name: 'Payroll & Wages', actions: ['view', 'create', 'edit', 'approve'] },
    ],
  },
  {
    code: 'parties',
    name: 'Customers & Suppliers',
    sortOrder: 10,
    features: [
      { code: 'customers', name: 'Customers', actions: ['view', 'create', 'edit', 'delete'] },
      { code: 'suppliers', name: 'Suppliers', actions: ['view', 'create', 'edit', 'delete'] },
      { code: 'customer_receipts', name: 'Customer Receipts', actions: ['view', 'create', 'edit', 'delete', 'approve'] },
      { code: 'supplier_payments', name: 'Supplier Payment Vouchers', actions: ['view', 'create', 'edit', 'delete', 'approve'] },
    ],
  },
  {
    code: 'reports',
    name: 'Reports & Dashboard',
    sortOrder: 11,
    features: [
      { code: 'ceo_dashboard', name: 'CEO Dashboard', actions: ['view'] },
      { code: 'reports', name: 'Reports', actions: ['view'] },
    ],
  },
  {
    code: 'webstore',
    name: 'Web Store Integration',
    sortOrder: 12,
    features: [
      { code: 'api_settings', name: 'API Settings', actions: ['view', 'edit'] },
      { code: 'orders', name: 'Online Orders', actions: ['view', 'edit', 'approve'] },
    ],
  },
];

export function buildPermissionKey(moduleCode, featureCode, action) {
  return `${moduleCode}.${featureCode}.${action}`;
}
